

#' @export
volumetric <- function(n, visit = "V1", ids = NULL) {
  ids <- handle_ids(ids)

  assessment_performed <- sample_yes_no(n)
  performed <- assessment_performed == "Yes"
  not_performed <- assessment_performed == "No"

  date_of_mri <- random_date(n, which_na = not_performed)
  assessment_date <- date_of_mri + sample(c(1:5, n, replace = TRUE))

  reason_not_performed <- reason_not_collected(n, which_na = performed)


  df <- data.frame(
    patient_id = ids,
    visit = visit,
    date_of_mri = date_of_mri,
    LBV = sample_numeric(n),
    LBVQC = sample_pass_fail(n, which_na = not_performed),
    LBVQCC = NA,
    KNBBSI = sample_numeric(n),
    KNBBSIQC = sample_pass_fail(n, which_na = not_performed),
    LHVL = sample_numeric(n),
    LHVR = sample_numeric(n),
    LHQCG = sample_pass_fail(n, which_na = not_performed),
    LHQCC = NA,
    LLHVL = sample_numeric(n),
    LLHLA = sample_numeric(n),
    LLHLPA = sample_numeric(n),
    LLHVR = sample_numeric(n),
    LLHLR = sample_numeric(n),
    LLHRPA = sample_numeric(n),
    LLHQCG = sample_pass_fail(n, which_na = not_performed),
    LLHQCC = NA,
    LVV = sample_numeric(n),
    LVVQC = sample_pass_fail(n, which_na = not_performed),
    LVVQCC = NA,
    LLVV = sample_numeric(n),
    LLVA = sample_numeric(n),
    LLPA = sample_numeric(n),
    LLVVQC = sample_pass_fail(n, which_na = not_performed),
    LLVVQCC = NA,
    PTIV = sample_numeric(n),
    PTIVQC = sample_pass_fail(n, which_na = not_performed),
    PTIVQCC = NA,
    LWMV = sample_numeric(n),
    LWMJVV = sample_numeric(n),
    LWMJVP = sample_numeric(n),
    LWMJCV = sample_numeric(n),
    LWMJCP = sample_numeric(n),
    LWMDV = sample_numeric(n),
    LWMDP = sample_numeric(n),
    LWMPVV = sample_numeric(n),
    LWMPVP = sample_numeric(n),
    LWMQC = sample_pass_fail(n, which_na = not_performed),
    LWMQCC = NA,
    LTVV = sample_numeric(n),
    LFVV = sample_numeric(n),
    LRACCU = sample_numeric(n),
    LLACCU = sample_numeric(n),
    LRAMYG = sample_numeric(n),
    LLAMYG = sample_numeric(n),
    LRCV = sample_numeric(n),
    LLCV = sample_numeric(n),
    LRCBEV = sample_numeric(n),
    LLCBEV = sample_numeric(n),
    LRCBWMV = sample_numeric(n),
    LLCBWMV = sample_numeric(n),
    LRCWMV = sample_numeric(n),
    LLCWMV = sample_numeric(n),
    LCSFV = sample_numeric(n),
    LRILVV = sample_numeric(n),
    LLILVV = sample_numeric(n),
    LRPALV = sample_numeric(n),
    LLPALV = sample_numeric(n),
    LRPUTV = sample_numeric(n),
    LLPUTV = sample_numeric(n),
    LRTHAPV = sample_numeric(n),
    LLTHAPV = sample_numeric(n),
    LRVENDCV = sample_numeric(n),
    LLVENDCV = sample_numeric(n),
    LCVLVIVV = sample_numeric(n),
    LCVLVIVII = sample_numeric(n),
    LCVLVIIIX = sample_numeric(n),
    LRBFBV = sample_numeric(n),
    LLBFBV = sample_numeric(n),
    LRACGCV = sample_numeric(n),
    LLACGCV = sample_numeric(n),
    LRAINSV = sample_numeric(n),
    LLAINSV = sample_numeric(n),
    LRAOGV = sample_numeric(n),
    LLAOGV = sample_numeric(n),
    LRANGV = sample_numeric(n),
    LLANGV = sample_numeric(n),
    LRCALCV = sample_numeric(n),
    LLCALCV = sample_numeric(n),
    LRCOPERV = sample_numeric(n),
    LLCOPERV = sample_numeric(n),
    LRCUNV = sample_numeric(n),
    LLCUNV = sample_numeric(n),
    LRENTAV = sample_numeric(n),
    LLENTAV = sample_numeric(n),
    LRFOPV = sample_numeric(n),
    LLFOPV = sample_numeric(n),
    LRFPV = sample_numeric(n),
    LLFPV = sample_numeric(n),
    LRFUSIGV = sample_numeric(n),
    LLFUSIGV = sample_numeric(n),
    LRGYRRV = sample_numeric(n),
    LLGYRRV = sample_numeric(n),
    LRINFOGV = sample_numeric(n),
    LLINFOGV = sample_numeric(n),
    LRINFTGV = sample_numeric(n),
    LLINFTGV = sample_numeric(n),
    LRLINGGV = sample_numeric(n),
    LLLINGGV = sample_numeric(n),
    LRLATOGV = sample_numeric(n),
    LLLATOGV = sample_numeric(n),
    LRMCINGGV = sample_numeric(n),
    LLMCINGGV = sample_numeric(n),
    LRMFCV = sample_numeric(n),
    LLMFCV = sample_numeric(n),
    LRMFGYV = sample_numeric(n),
    LMFGYV = sample_numeric(n),
    LRMOCCGV = sample_numeric(n),
    LLMOCCGV = sample_numeric(n),
    LRMORBGV = sample_numeric(n),
    LLMORBGV = sample_numeric(n),
    LRPOSTGV = sample_numeric(n),
    LLPOSTGV = sample_numeric(n),
    LRPREGV = sample_numeric(n),
    LLPREGV = sample_numeric(n),
    LRSFGV = sample_numeric(n),
    LLSFGV = sample_numeric(n),
    LRSFGMV = sample_numeric(n),
    LLSFGMV = sample_numeric(n),
    LRMTGV = sample_numeric(n),
    LLMTGV = sample_numeric(n),
    LROCCPV = sample_numeric(n),
    LLOCCPV = sample_numeric(n),
    LROCFUGV = sample_numeric(n),
    LLOCFUGV = sample_numeric(n),
    LROPIFGV = sample_numeric(n),
    LLOPIFGV = sample_numeric(n),
    LRORIFGV = sample_numeric(n),
    LLORIFGV = sample_numeric(n),
    LRPCINGV = sample_numeric(n),
    LLPCINGV = sample_numeric(n),
    LRPRECV = sample_numeric(n),
    LLPRECV = sample_numeric(n),
    LRPAHIPGV = sample_numeric(n),
    LLPAHIPGV = sample_numeric(n),
    LRPINSV = sample_numeric(n),
    LLPINSV = sample_numeric(n),
    LRPAROPV = sample_numeric(n),
    LLPAROPV = sample_numeric(n),
    LRPGV = sample_numeric(n),
    LLPGV = sample_numeric(n),
    LRPOBGV = sample_numeric(n),
    LLPOBGV = sample_numeric(n),
    LRPLANPV = sample_numeric(n),
    LLPLANPV = sample_numeric(n),
    LRPRGV = sample_numeric(n),
    LLPRGV = sample_numeric(n),
    LRPLANTV = sample_numeric(n),
    LLPLANTV = sample_numeric(n),
    LRSUBCAV = sample_numeric(n),
    LLSUBCAV = sample_numeric(n),
    LRSUPMCV = sample_numeric(n),
    LLSUPMCV = sample_numeric(n),
    LRSUPRGV = sample_numeric(n),
    LLSUPRGV = sample_numeric(n),
    LRSUOGV = sample_numeric(n),
    LLSUOGV = sample_numeric(n),
    LRSUPALV = sample_numeric(n),
    LLSUPALV = sample_numeric(n),
    LRSTPGV = sample_numeric(n),
    LLSTPGV = sample_numeric(n),
    LRTPV = sample_numeric(n),
    LLTPV = sample_numeric(n),
    LRTRIFGV = sample_numeric(n),
    LLTRIFGV = sample_numeric(n),
    LRTTGV = sample_numeric(n),
    LLTTGV = sample_numeric(n),
    LMIDBV = sample_numeric(n),
    LPONSV = sample_numeric(n),
    LMEDUV = sample_numeric(n),
    LSCEREPV = sample_numeric(n),
    assessment_performed = assessment_performed,
    assessment_date = assessment_date,
    reason_not_performed = reason_not_performed
  )
}

sample_pass_fail <- function(n, which_na = c()) {
  x <- sample(c("Pass", "Fail"), n, replace = TRUE)
  remove_indices(x, which_na)
}
